# Generated by Django 5.1.3 on 2024-11-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('modelo', models.TextField(max_length=100)),
                ('serial', models.TextField(max_length=100)),
                ('area', models.TextField(max_length=100)),
                ('responsable', models.TextField(max_length=100)),
                ('foto', models.TextField(max_length=100)),
            ],
        ),
    ]
