# Generated by Django 5.1.3 on 2024-11-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
